// Generated by CoffeeScript 1.4.0

/*
  その他
*/


(function() {
  var food, x, _i, _len, _ref;

  _ref = ['sushi', 'tenpura', 'sukiyaki'];
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    food = _ref[_i];
    eat(food);
  }

  x = 2;

  if (x !== 1) {
    x;

  }

  while (x !== 5) {
    x++;
  }

}).call(this);
