// Generated by CoffeeScript 1.4.0

/*
  配列
*/


(function() {
  var bitlist, members, music, numAry, yamada, yasunishi;

  music = ["C", "D", "E", "G", "F", "A", "H"];

  music[6] = "B";

  bitlist = [1, 0, 1, 0, 0, 1, 1, 1, 0];

  numAry = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

  yamada = {
    name: "yoshihiro",
    age: 27
  };

  yasunishi = [];

  yasunishi["name"] = "tsuyoshi";

  yasunishi["age"] = 3;

  members = {
    yamada: {
      name: "yoshihiro",
      age: 28
    },
    yasunishi: {
      name: "tsuyoshi",
      age: 3
    }
  };

}).call(this);
