// Generated by CoffeeScript 1.4.0

/*
  関数
*/


(function() {
  var minus, multi, square, sum,
    __slice = [].slice;

  square = function(x) {
    return x * x;
  };

  sum = function(n, m) {
    return n + m;
  };

  minus = function(n, m) {
    if (n == null) {
      n = 2;
    }
    if (m == null) {
      m = 4;
    }
    return n - m;
  };

  sum = function() {
    var num, nums, result, _i, _len;
    nums = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    result = 0;
    for (_i = 0, _len = nums.length; _i < _len; _i++) {
      num = nums[_i];
      result += num;
    }
    return result;
  };

  multi = function(n) {
    if (n < 2) {
      return square(n, 5);
    } else {
      return sum(n, 2);
    }
  };

}).call(this);
