// Generated by CoffeeScript 1.4.0

/*
  変数
*/


(function() {
  var f, hello, html, i, name, sum;

  i = 225;

  f = 5.23;

  sum = i + f + 3 * 6;

  name = "安西";

  hello = "こんにちは、" + name + "さん";

  hello = "こんにちは、" + name + "さん";

  html = '<ul>\n  <li>アプリを作ろう！　Android入門 ～ゼロから学ぶアプリの作成から公開まで</li>\n  <li>TECHNICAL MASTER　はじめてのJSP＆サーブレット　Eclipse 3.7 Indigo＋Tomcat 7対応版</li>\n  <li>Windows Azure Platform開発入門</li>\n</ul>';

}).call(this);
